{% set version = "2.5.0" %}
{% set name = "fflas-ffpack" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/linbox-team/fflas-ffpack/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: dafb4c0835824d28e4f823748579be6e4c8889c9570c6ce9cce1e186c3ebbb23
  patches:
    - 0001-Do-not-run-host-commands-when-cross-compiling.patch
    - 0002-Disable-storage-transpose-tests-on-macOS.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('fflas-ffpack') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
    - automake
    - autoconf
    - make
  host:
    - libblas
    - libcblas
    - liblapack
    - givaro
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/fflas-ffpack/ffpack/ffpack.h
    - test -f ${PREFIX}/lib/libfflas.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfflas.so         # [linux]
    - test -f ${PREFIX}/lib/libffpack.dylib     # [osx]
    - test -f ${PREFIX}/lib/libffpack.so        # [linux]

about:
  home: http://linbox-team.github.io/fflas-ffpack/
  license: LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Finite Field Linear Algebra Subroutines / Package
  dev_url: https://github.com/linbox-team/fflas-ffpack

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
