{% set version = "2.4.0" %}
{% set name = "fflas-ffpack" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/linbox-team/fflas-ffpack/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07312bdb85681094e12b8f0087f29c956f99e637056a1011952af29562710d5e

build:
  number: 0
  skip: true  # [win]
  features:
  run_exports:
    - {{ pin_subpackage('fflas-ffpack') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
    - automake
    - autoconf
  host:
    - libblas
    - liblapack
    - givaro
    - gsl
    - gmp
  run:
    - givaro
    - gsl
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/fflas-ffpack/ffpack/ffpack.h
    - test -f ${PREFIX}/lib/libfflas.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfflas.so         # [linux]
    - test -f ${PREFIX}/lib/libffpack.dylib     # [osx]
    - test -f ${PREFIX}/lib/libffpack.so        # [linux]

about:
  home: http://linbox-team.github.io/fflas-ffpack/
  license: LGPLv2.1+
  license_file: COPYING.LESSER
  summary: Finite Field Linear Algebra Subroutines / Package
  dev_url: https://github.com/linbox-team/fflas-ffpack

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
