travis:
  secure:
    BINSTAR_TOKEN: DyjhHpV2/f1g4KF2uHmXzNn4RWSEZqxXDWRHJ9Pn9e2lHpxVrf0aWNPQKRnuJiHU6TlzKbVQjI2E4wpsFmW3S2GXP5E3uQiNBUp3KE8uDiwIJVmvjuHSMw08h9jo++icpgxoj00DjQzGNWwVp0savm65SrQ+21ljKxeK0IGuFMRhs1ibU0m5V2Zo7sEBdmQt1HVIQUygA6186MTwuL4s4r8FjV+YRIzeNPpkdYuvgH0jslKmI1EulxfEfiJvttjCh4PMu5ByUgij91NdzJn6TO1jCkOH+i2rZVX7VQD7hvJPwj++UrH5lTThRxj94iCzdSrS+bFJFKZt1SsWblu/ASSc00jGeEt3yNbvHkdm3e58OUqapUsWbwXWGsmRVP/utZ4SdNEMAomXpurqH1MTvtVZWdBSD38EhZwWPvLMNfqgroZh2Qh/fMa7WOhCh+L8kBdlKi4Tq38Rnu17OExDffBlNPdwxNEMQ4K1sCP/uX3wQuyugUPUyQ5ImfVFshkjpJ5ip1sD0UayTUuZG+Hp7h908Xf1gRl30QLU8SpfJe3yh+38TRndYfUFQR63lyOkZwRi+clgAa220FbyEuBdYPCqjxDz/dWxseJetbqSAB9/+Mwfv2cnm5bRYC8DZ4pK9uRggA1UioStttkIXl+PUosN3LDuaD6E+PDQGYR8f5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
