travis:
  secure:
    BINSTAR_TOKEN: sReoMfZNm6YaZnrdwRFhK/PmThvifdZ5leLEin4HhRN4/r0cmKP1k8tQ+plhZvnz+PvRD/lh5NysoeTB3sOmoacQRBdgagFLmSgVg7xU+G5pmKcuD3nyR9B8puZd8KAwoFiTRzwcKlg+U/hD1gwm/c1/6NEma6NPhAaUG4U2A6njWHs+4cW1YVTXQVchzdYcauSHiTUmT7bO0x+l3mEUQfO36VGCwpCTaI0dbX6kXXnlhNSWk0Y8KdXEINf/QppotnxImGGkJeKsPKIaNL+8iSUe/p4ArturX8HBCGrRvGyQxdClJS8hYG5OJKEs7fusu3Hw5ESQbaVWHsg3rjcDXRCNUqaGyHCHnqv3XRfNyfMWpUoHk7MS35WkOmijHlGqHfnquhM/5P7TB8SFsxQEEdXf4rCqxhJVN3yWIYn3QX+yJC1cvW3O3PWsR+EkhcYCiITd/IWvNdSXOaph6KFmgqKniXw28DtJWKnS3mknEn4W93Dty15oTqneQFbMEWH/PZSL4TSro4GwEDYKVOozzqouvvzzFmjStILy2aSNi7Vc6N2pUXYXPkMfvZXwI5FFMxB7Q5aRvQsVDcOzEa9wQ8/w9R9XtgU5D6XLCR+VesZmVCsxL0wIFrKFBvFywij8ggt8ArZpMF2GdKpzKywAZyqYdctiP3MfQ0ktmudFeY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
